# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CampusKey' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CampusKey
  pod "GoogleMaps"
  pod "GooglePlaces"
  pod "RealmSwift"
  pod "Firebase/Core"
  pod "Firebase/Analytics"
  pod "Firebase/Database"
  
  target 'CampusKeyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CampusKeyUITests' do
    # Pods for testing
  end

end
